sectionsToRender:
  - about
  - work
  - projects
  - skills
  - connect

sections:
  about:
    id: about
    greeting: "Hi, I'm"
    title: "Zack M Fleischman"
    subtitle: "I build software."
    backgroundImage: ../../assets/images/artsy3.jpg 

  work:
    id: work
    menuTitle: Work
    title: "What I’ve built professionally"
    jobs:
      - company: Strypes
        product: "3D Fashion Configurator"
        title: "Cofounder and CTO"
        description: "As their CTO, I am leading the technology charge, solving the problem of 'How do we build this 3D experience easily and quickly?'.\n\n
To do this, I’m bringing Strypes to the forefront of the 3D Technology utilizing several different tools from various different industries such as the Gaming, 3D Web Design, 3D Digitization, and VR/AR.
"
        imageUrl: ../../assets/images/StrypesLogo.png

      - company: Microsoft
        product: XBox
        title: "Software Engineer"
        description: "XBox 360, Xbox One, and Kinect. Rapid prototyping blah blah blah"
        imageUrl: microsoft.png

  projects:
    id: projects
    menuTitle: Projects
    title: "What I've built for fun"
    projects:
      - title: Mandelbrot Set Zoomer
        description: Zoom in on the Mandelbrot Set
        imageUrl: mandelbrot.gif
        sourceCodeUrl: mandelbrot.html

      - title: Circle Magic
        description: Wooooaahhhh circles!
        imageUrl: circles.gif
        sourceCodeUrl: circles.html

  skills: 
    id: skills
    menuTitle: Skills
    title: "My Skillset"
    skillGroups:
      - title: "High Level Skills"
        skills:
          - skillName: "Software Architecture"
          - skillName: "Engineering Management"
          - skillName: "Business Development"
          - skillName: "Web Development"
          - skillName: "Game Development"
          - skillName: "Tooling and Automation"
          - skillName: "DevOps"
      - title: "Languages"
        skills:
          - skillName: "Typescript/Javascript"
          - skillName: "C#"
          - skillName: "C/C++"
          - skillName: "Python"
          - skillName: "Bash"
          - skillName: "HTML/CSS/SASS"
          - skillName: "Processing"
      - title: "Frameworks & Tools"
        skills:
          - skillName: "Unity 3D"
          - skillName: "BabylonJS"
          - skillName: "React/Redux"
          - skillName: "AWS"
          - skillName: "Node"
          - skillName: "Jenkins"
          - skillName: "Mocha"

  connect:
    id: connect
    title: "Connect With Me"
    menuTitle: Connect
    hireMe:
      - github
    followMe: 
      - twitter
      - linkedIn
      - angelList
    emailMe: ZackMFleischman+website@gmail.com

socialMedia:
  twitter: 
    id: twitter
    label: Twitter
    url: https://www.twitter.com/ZackMFleischman
    icon: ../../assets/images/twitter_logo.png

  linkedIn: 
    id: linkedIn
    label: LinkedIn
    url: https://www.linkedIn.com/in/ZackMFleischman
    icon: ../../assets/images/linkedin_logo.png 

  angelList:
    id: angelList
    label: AngelList
    url: https://angel.co/zackmfleischman
    icon: ../../assets/images/angellist_logo.png

  github:
    id: github
    label: Github
    url: https://github.com/ZackMFleischman
    icon: ../../assets/images/github_logo.png